// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUnXmuavSzZ48zFBCP_L7cIEc3ofQcjE',
    appId: '1:538796607449:web:1e6f949a42767d2c8ffbc8',
    messagingSenderId: '538796607449',
    projectId: 'daily-gist-9bc06',
    authDomain: 'daily-gist-9bc06.firebaseapp.com',
    storageBucket: 'daily-gist-9bc06.appspot.com',
    measurementId: 'G-EPEG6TKHJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd1AJa-Ok9-on5uBa6ofxGXbkP_gAXUrk',
    appId: '1:538796607449:android:16a01c26434a05d38ffbc8',
    messagingSenderId: '538796607449',
    projectId: 'daily-gist-9bc06',
    storageBucket: 'daily-gist-9bc06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVBjqJTl86Umcb4-2pCz2qbdE56W8cCVo',
    appId: '1:538796607449:ios:9046050f1f73ba198ffbc8',
    messagingSenderId: '538796607449',
    projectId: 'daily-gist-9bc06',
    storageBucket: 'daily-gist-9bc06.appspot.com',
    iosBundleId: 'com.example.gtDaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVBjqJTl86Umcb4-2pCz2qbdE56W8cCVo',
    appId: '1:538796607449:ios:21d6663211a1e22f8ffbc8',
    messagingSenderId: '538796607449',
    projectId: 'daily-gist-9bc06',
    storageBucket: 'daily-gist-9bc06.appspot.com',
    iosBundleId: 'com.example.gtDaily.RunnerTests',
  );
}
